CREATE SEQUENCE CONTATOS_SEQ;

CREATE TABLE TBL_CONTATOS (
    ID INTEGER DEFAULT CONTATOS_SEQ.NEXTVAL NOT NULL,
    NOME VARCHAR2(100) NOT NULL,
    EMAIL VARCHAR2(100) NOT NULL,
    DATA_NASCIMENTO DATE NOT NULL
);