CREATE TABLE LIVROS (
    ID INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    TITULO_LIVRO VARCHAR(70),
    AUTOR VARCHAR(90),
    EDITORA VARCHAR(70),
    ANO_PUBLICACAO DATE,
    GENERO VARCHAR(30),
    PAGINAS_LIDAS INT NOT NULL,
    AVALIACAO INT NOT NULL,
    ID_BIBLIOTECA INT NOT NULL,  -- Adiciona a coluna e marca como NOT NULL
    FOREIGN KEY (ID_BIBLIOTECA) REFERENCES BIBLIOTECAS(ID)
);